const systemState={group:'light',presence:false,biodynamic:false,humidity:45,ventilation:false,floor:false,music:false,volume:35,leak:false,smoke:false,gas:false,armed:false,locked:true,gate:false,window:false,irrigation:false,robot:false,tariff:false};
const systemDefaults={...systemState};
const systemCopy={
 uk:{groups:['Світло','Клімат','Медіа','Безпека','Приводи','Побут'],map:'Стан систем',presence:'Імітація присутності',biodynamic:'Біодинамічне світло',humidity:'Вологість',ventilation:'Посилена вентиляція',floor:'Тепла підлога',music:'Мультирум',volume:'Гучність',leak:'Симуляція протікання',smoke:'Симуляція диму',gas:'Симуляція витоку газу',armed:'Охорона периметра',locked:'Замок вхідних дверей',gate:'Ворота',window:'Провітрювання вікном',irrigation:'Автополив',robot:'Робот-пилосос',tariff:'Перенесення споживання на ніч',alloff:'Вимкнути все й увімкнути охорону',on:'Увімкнено',off:'Вимкнено',open:'Відкрито',closed:'Закрито',lockedState:'Замкнено',unlocked:'Відімкнено',valve:'Вода перекрита',gasOff:'Газ перекрито · сповіщення',normal:'Датчики в нормі',alarm:'Виявлено дим · сповіщення',demo:'Демонстрація · без підключення до обладнання',labels:['Світло','Клімат','Медіа','Вода','Доступ','Двір','Прибирання'],status:'Активні системи',idle:'Налаштування застосовано',robotRun:'Прибирання триває',watering:'Полив активний',night:'Побутові задачі заплановано на ніч'},
 en:{groups:['Lighting','Climate','Media','Security','Drives','Home'],map:'System status',presence:'Presence simulation',biodynamic:'Biodynamic lighting',humidity:'Humidity',ventilation:'Boost ventilation',floor:'Underfloor heating',music:'Multiroom audio',volume:'Volume',leak:'Simulate a water leak',smoke:'Simulate smoke',gas:'Simulate a gas leak',armed:'Perimeter security',locked:'Entrance door lock',gate:'Gate',window:'Window ventilation',irrigation:'Lawn irrigation',robot:'Robot vacuum',tariff:'Shift consumption to night',alloff:'All off and arm security',on:'On',off:'Off',open:'Open',closed:'Closed',lockedState:'Locked',unlocked:'Unlocked',valve:'Water shut off',gasOff:'Gas shut off · notification',normal:'Sensors normal',alarm:'Smoke detected · notification',demo:'Demonstration · no connected equipment',labels:['Light','Climate','Media','Water','Access','Garden','Cleaning'],status:'Active systems',idle:'Settings applied',robotRun:'Cleaning in progress',watering:'Irrigation active',night:'Household tasks scheduled for night'}
};
function toggleRow(key){const t=systemCopy[locale];return `<div class="system-toggle-row"><span>${t[key]}</span><button data-system="${key}" aria-label="${t[key]}" aria-pressed="${systemState[key]}"></button></div>`;}
function rangeRow(key,min,max,unit){const t=systemCopy[locale];return `<label class="range-label" for="system-${key}">${t[key]}<output data-system-output="${key}">${systemState[key]}${unit}</output></label><input type="range" id="system-${key}" aria-label="${t[key]}" data-system-range="${key}" min="${min}" max="${max}" value="${systemState[key]}">`;}
function systemMap(){return `<svg class="system-map" viewBox="0 0 340 158" role="img" aria-label="${systemCopy[locale].map}"><g class="map-shell"><path d="M30 38H208V20H310V135H30Z"/><path d="M30 90H128V135M128 38V90H208V135M208 20V90H310"/><path class="map-gate" d="M260 135h35"/></g><path class="map-heat" d="M140 104h55m-55 8h55m-55 8h55"/><path class="map-air" d="M228 43h53m-46 9h45m-52 9h53"/><path class="map-robot-route" d="M49 62H110V78H49V62"/><g class="map-garden"><circle cx="14" cy="49" r="5"/><circle cx="14" cy="70" r="5"/><circle cx="14" cy="91" r="5"/><path d="M8 35L19 30M6 28L14 19M18 35L27 24"/></g><g class="map-node map-light"><circle cx="77" cy="61" r="12"/><path d="M77 44v-5m0 39v5M60 61h-5m39 0h5"/></g><g class="map-node map-media"><circle cx="171" cy="62" r="9"/><path d="M183 51q14 11 0 22m-25-22q-14 11 0 22"/></g><g class="map-node map-water"><path d="M266 97q-15 18 0 24q15-6 0-24Z"/></g><circle class="map-robot" cx="50" cy="62" r="6"/><path class="map-window" d="M243 20h42"/><g class="map-lock"><rect x="224" y="109" width="13" height="12" rx="2"/><path d="M227 109v-5q4-6 7 0v5"/></g><text x="37" y="153">${locale==='uk'?'Схема взаємодії систем':'System interaction diagram'}</text></svg>`;}
function automationPanelHTML(ui){const t=systemCopy[locale],keys=['light','climate','media','security','drives','home'];return `<div class="automation-heading"><div><span class="eyebrow">${ui.preset}</span><h3 class="preset-name"></h3></div><span class="status-dot" aria-hidden="true"></span></div><div class="preset-tabs" role="group" aria-label="${ui.preset}">${ui.presets.map((p,i)=>`<button data-preset="${i}" aria-pressed="false">${p}</button>`).join('')}</div>${systemMap()}<div class="system-group-tabs" role="group" aria-label="${t.map}">${keys.map((key,i)=>`<button data-system-group="${key}" aria-pressed="${key===systemState.group}">${t.groups[i]}</button>`).join('')}</div>
<section data-system-section="light"><label class="range-label" for="light-control">${ui.light}<output id="light-output" for="light-control"></output></label><input id="light-control" aria-label="${ui.light}" data-control="light" type="range" min="0" max="100" step="5" value="${automation.light}">${toggleRow('presence')}${toggleRow('biodynamic')}</section>
<section data-system-section="climate"><label class="range-label" for="climate-control">${ui.climate}<output id="climate-output" for="climate-control"></output></label><input id="climate-control" aria-label="${ui.climate}" data-control="temp" type="range" min="16" max="28" step="1" value="${automation.temp}">${rangeRow('humidity',30,65,'%')}${toggleRow('ventilation')}${toggleRow('floor')}</section>
<section data-system-section="media">${toggleRow('music')}${rangeRow('volume',0,100,'%')}<p class="system-hint">${t.demo}</p></section>
<section data-system-section="security">${toggleRow('leak')}${toggleRow('smoke')}${toggleRow('gas')}${toggleRow('armed')}<div class="sensor-status" role="status"></div><div class="security-state"></div></section>
<section data-system-section="drives"><div class="curtain-control"><span>${ui.curtains}</span><button data-curtains aria-pressed="false"></button></div>${toggleRow('locked')}${toggleRow('gate')}${toggleRow('window')}</section>
<section data-system-section="home">${toggleRow('irrigation')}${toggleRow('robot')}${toggleRow('tariff')}<button class="all-off" data-all-off>${t.alloff} ↗</button></section><div class="system-summary" role="status"></div><div class="automation-foot"><span>${ui.demo}</span><button data-reset>${ui.reset} ↺</button></div>`;}
function updateSystems(){if(activeChapter!==4)return;const p=document.querySelector('.automation-panel'),t=systemCopy[locale];p.querySelectorAll('[data-system-section]').forEach(e=>e.hidden=e.dataset.systemSection!==systemState.group);p.querySelectorAll('[data-system-group]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.systemGroup===systemState.group)));p.querySelectorAll('[data-system]').forEach(b=>{const k=b.dataset.system,on=systemState[k];b.setAttribute('aria-pressed',String(on));b.textContent=k==='locked'?(on?t.lockedState:t.unlocked):['gate','window'].includes(k)?(on?t.open:t.closed):(on?t.on:t.off);});p.querySelectorAll('[data-system-output]').forEach(o=>o.textContent=systemState[o.dataset.systemOutput]+'%');p.querySelectorAll('[data-system-range]').forEach(r=>r.value=systemState[r.dataset.systemRange]);
p.querySelector('.sensor-status').textContent=[systemState.leak?t.valve:'',systemState.smoke?t.alarm:'',systemState.gas?t.gasOff:''].filter(Boolean).join(' · ')||t.normal;
const flags={light:automation.light>0,air:systemState.ventilation,heat:systemState.floor,media:systemState.music,water:systemState.leak,garden:systemState.irrigation,robot:systemState.robot,lock:systemState.locked,gate:systemState.gate,window:systemState.window,alarm:systemState.smoke||systemState.gas||systemState.armed};Object.entries(flags).forEach(([key,on])=>p.classList.toggle('system-'+key,on));
const notes=[systemState.robot?t.robotRun:'',systemState.irrigation?t.watering:'',systemState.tariff?t.night:''];p.querySelector('.system-summary').textContent=notes.filter(Boolean).join(' · ')||t.idle;
const stage=document.querySelector('.story-sticky');Object.entries(systemState).forEach(([key,v])=>{if(typeof v==='boolean')stage.classList.toggle('device-'+key,v);});stage.style.setProperty('--humidity',systemState.humidity/100);stage.style.setProperty('--volume',systemState.volume/100);
let visuals=document.querySelector('.device-effects');if(!visuals){visuals=document.createElement('div');visuals.className='device-effects';visuals.setAttribute('aria-hidden','true');visuals.innerHTML='<div class="air-ribbons"><i></i><i></i><i></i></div><div class="floor-warmth"></div><div class="audio-rings"><i></i><i></i><i></i></div><div class="robot-visual"></div><div class="water-alert"></div><div class="garden-particles"></div>';document.querySelector('.stage-visual').append(visuals);}
visuals.style.display='';stage.querySelector('.water-alert').textContent=systemState.smoke?t.alarm:systemState.gas?t.gasOff:t.valve;
}
function systemClick(b){if(b.dataset.preset!==undefined){const i=Number(b.dataset.preset),group=systemState.group;Object.assign(systemState,systemDefaults,{group,armed:i===3,music:i===1||i===2,biodynamic:i===0,locked:true});}if(b.dataset.systemGroup){systemState.group=b.dataset.systemGroup;updateSystems();}if(b.dataset.system){const key=b.dataset.system;systemState[key]=!systemState[key];if(key==='armed')automation.armed=systemState.armed;automation.preset=-1;updateAutomation();}if(b.hasAttribute('data-all-off')){Object.assign(systemState,systemDefaults,{group:'home',armed:true});automation={preset:3,...presets[3]};updateAutomation();}if(b.hasAttribute('data-reset')){Object.assign(systemState,systemDefaults);updateSystems();}}
