const systemState={group:'light',presence:false,biodynamic:false,humidity:45,ventilation:false,floor:false,music:false,volume:35,leak:false,smoke:false,gas:false,armed:false,locked:true,gate:false,window:false,irrigation:false,robot:false,tariff:false};
const systemDefaults={...systemState};
const systemCopy={
 uk:{groups:['Світло','Клімат','Медіа','Безпека','Приводи','Побут'],map:'Стан систем',presence:'Імітація присутності',biodynamic:'Біодинамічне світло',humidity:'Вологість',ventilation:'Посилена вентиляція',floor:'Тепла підлога',music:'Мультирум',volume:'Гучність',leak:'Симуляція протікання',smoke:'Симуляція диму',gas:'Симуляція витоку газу',armed:'Охорона периметра',locked:'Замок вхідних дверей',gate:'Ворота',window:'Провітрювання вікном',irrigation:'Автополив',robot:'Робот-пилосос',tariff:'Перенесення споживання на ніч',alloff:'Вимкнути все й увімкнути охорону',on:'Увімкнено',off:'Вимкнено',open:'Відкрито',closed:'Закрито',lockedState:'Замкнено',unlocked:'Відімкнено',valve:'Вода перекрита',gasOff:'Газ перекрито · сповіщення',normal:'Датчики в нормі',alarm:'Виявлено дим · сповіщення',demo:'Демонстрація · без підключення до обладнання',labels:['Світло','Клімат','Медіа','Вода','Доступ','Двір','Прибирання'],status:'Активні системи',idle:'Налаштування застосовано',robotRun:'Прибирання триває',watering:'Полив активний',night:'Побутові задачі заплановано на ніч'},
 en:{groups:['Lighting','Climate','Media','Security','Drives','Home'],map:'System status',presence:'Presence simulation',biodynamic:'Biodynamic lighting',humidity:'Humidity',ventilation:'Boost ventilation',floor:'Underfloor heating',music:'Multiroom audio',volume:'Volume',leak:'Simulate a water leak',smoke:'Simulate smoke',gas:'Simulate a gas leak',armed:'Perimeter security',locked:'Entrance door lock',gate:'Gate',window:'Window ventilation',irrigation:'Lawn irrigation',robot:'Robot vacuum',tariff:'Shift consumption to night',alloff:'All off and arm security',on:'On',off:'Off',open:'Open',closed:'Closed',lockedState:'Locked',unlocked:'Unlocked',valve:'Water shut off',gasOff:'Gas shut off · notification',normal:'Sensors normal',alarm:'Smoke detected · notification',demo:'Demonstration · no connected equipment',labels:['Light','Climate','Media','Water','Access','Garden','Cleaning'],status:'Active systems',idle:'Settings applied',robotRun:'Cleaning in progress',watering:'Irrigation active',night:'Household tasks scheduled for night'}
};
function toggleRow(key){const t=systemCopy[locale];return `<div class="system-toggle-row"><span>${t[key]}</span><button data-system="${key}" aria-label="${t[key]}" aria-pressed="${systemState[key]}"></button></div>`;}
function rangeRow(key,min,max,unit){const t=systemCopy[locale];return `<label class="range-label" for="system-${key}">${t[key]}<output data-system-output="${key}">${systemState[key]}${unit}</output></label><input type="range" id="system-${key}" aria-label="${t[key]}" data-system-range="${key}" min="${min}" max="${max}" value="${systemState[key]}">`;}
function automationPanelHTML(ui){const t=systemCopy[locale],keys=['light','climate','media','security','drives','home'];return `<div class="automation-heading"><div><span class="eyebrow">${ui.preset}</span><h3 class="preset-name"></h3></div><span class="status-dot" aria-hidden="true"></span></div><div class="preset-tabs" role="group" aria-label="${ui.preset}">${ui.presets.map((p,i)=>`<button data-preset="${i}" aria-pressed="false">${p}</button>`).join('')}</div><div class="scene-preview"></div><div class="system-group-tabs" role="group" aria-label="${t.map}">${keys.map((key,i)=>`<button data-system-group="${key}" aria-pressed="${key===systemState.group}">${t.groups[i]}</button>`).join('')}</div>
<section data-system-section="light"><label class="range-label" for="light-control">${ui.light}<output id="light-output" for="light-control"></output></label><input id="light-control" aria-label="${ui.light}" data-control="light" type="range" min="0" max="100" step="5" value="${automation.light}">${toggleRow('presence')}${toggleRow('biodynamic')}</section>
<section data-system-section="climate"><label class="range-label" for="climate-control">${ui.climate}<output id="climate-output" for="climate-control"></output></label><input id="climate-control" aria-label="${ui.climate}" data-control="temp" type="range" min="16" max="28" step="1" value="${automation.temp}">${rangeRow('humidity',30,65,'%')}${toggleRow('ventilation')}${toggleRow('floor')}</section>
<section data-system-section="media">${toggleRow('music')}${rangeRow('volume',0,100,'%')}<p class="system-hint">${t.demo}</p></section>
<section data-system-section="security">${toggleRow('leak')}${toggleRow('smoke')}${toggleRow('gas')}${toggleRow('armed')}<div class="sensor-status" role="status"></div><div class="security-state"></div></section>
<section data-system-section="drives"><div class="curtain-control"><span>${ui.curtains}</span><button data-curtains aria-pressed="false"></button></div>${toggleRow('locked')}${toggleRow('gate')}${toggleRow('window')}</section>
<section data-system-section="home">${toggleRow('irrigation')}${toggleRow('robot')}${toggleRow('tariff')}<button class="all-off" data-all-off>${t.alloff} ↗</button></section><div class="system-summary" role="status"></div><div class="automation-foot"><span>${ui.demo}</span><button data-reset>${ui.reset} ↺</button></div>`;}
function updateSystems(){if(activeChapter!==4)return;const p=document.querySelector('.automation-panel'),t=systemCopy[locale];p.querySelectorAll('[data-system-section]').forEach(e=>e.hidden=e.dataset.systemSection!==systemState.group);p.querySelectorAll('[data-system-group]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.systemGroup===systemState.group)));p.querySelectorAll('[data-system]').forEach(b=>{const k=b.dataset.system,on=systemState[k];b.setAttribute('aria-pressed',String(on));b.textContent=k==='locked'?(on?t.lockedState:t.unlocked):['gate','window'].includes(k)?(on?t.open:t.closed):(on?t.on:t.off);});p.querySelectorAll('[data-system-output]').forEach(o=>o.textContent=systemState[o.dataset.systemOutput]+'%');p.querySelectorAll('[data-system-range]').forEach(r=>r.value=systemState[r.dataset.systemRange]);
p.querySelector('.sensor-status').textContent=[systemState.leak?t.valve:'',systemState.smoke?t.alarm:'',systemState.gas?t.gasOff:''].filter(Boolean).join(' · ')||t.normal;
const flags={light:automation.light>0,air:systemState.ventilation,heat:systemState.floor,media:systemState.music,water:systemState.leak,garden:systemState.irrigation,robot:systemState.robot,lock:systemState.locked,gate:systemState.gate,window:systemState.window,alarm:systemState.smoke||systemState.gas||systemState.armed};Object.entries(flags).forEach(([key,on])=>p.classList.toggle('system-'+key,on));
const notes=[systemState.robot?t.robotRun:'',systemState.irrigation?t.watering:'',systemState.tariff?t.night:''];p.querySelector('.system-summary').textContent=notes.filter(Boolean).join(' · ')||t.idle;
const stage=document.querySelector('.story-sticky');Object.entries(systemState).forEach(([key,v])=>{if(typeof v==='boolean')stage.classList.toggle('device-'+key,v);});stage.style.setProperty('--humidity',systemState.humidity/100);stage.style.setProperty('--volume',systemState.volume/100);
let visuals=document.querySelector('.device-effects');if(!visuals){visuals=document.createElement('div');visuals.className='device-effects';document.querySelector('.stage-visual').append(visuals);}visuals.style.display='';updateScenePreview();
}
function systemClick(b){if(b.dataset.preset!==undefined){const i=Number(b.dataset.preset),group=systemState.group;Object.assign(systemState,systemDefaults,{group,armed:i===3,music:i===1||i===2,biodynamic:i===0,locked:true});}if(b.dataset.systemGroup){systemState.group=b.dataset.systemGroup;updateAutomation();}if(b.dataset.system){const key=b.dataset.system;systemState[key]=!systemState[key];if(key==='armed')automation.armed=systemState.armed;automation.preset=-1;updateAutomation();}if(b.hasAttribute('data-all-off')){Object.assign(systemState,systemDefaults,{group:'home',armed:true});automation={preset:3,...presets[3]};updateAutomation();}if(b.hasAttribute('data-reset')){Object.assign(systemState,systemDefaults);updateSystems();}}

function automationVisualBeat(){const beat=frames[activeFrame].beat;return {climate:1,security:2,drives:3,home:3,media:0}[systemState.group]??(beat===0?0:1);}
function automationSceneAsset(){return [automation.asset||'interior','kitchen','facade','model'][automationVisualBeat()];}
function sceneDiagram(){const b=automationVisualBeat();
 const room='<path d="M65 130L185 60L420 105L320 210Z M65 130V245L320 325L420 220V105 M320 210V325"/><path d="M185 60V175L65 245M185 175L320 210"/>';
 const scenes=[
 room+'<g class="scene-furniture"><path d="M130 190L220 215V250L130 225Z M220 215L265 189V224L220 250 M130 190L175 164L265 189"/><path d="M270 267l45-26 42 12-46 30Z"/></g><g class="scene-sound"><circle cx="185" cy="208" r="36"/><circle cx="185" cy="208" r="55"/></g>',
 room+'<path class="scene-counter" d="M105 145l68-38 15 5v63l-68 38-15-5Z M220 232l53-30 39 12-53 30Z"/><g class="scene-air"><path d="M215 107q80 10 50 70t60 65 M240 110q80 10 50 70t60 65 M265 113q80 10 50 70t60 65"/></g><g class="scene-heat"><path d="M130 242l110 35 85-47M150 230l90 29 68-38M171 220l69 22 49-27"/></g>',
 '<path d="M60 175L180 100L400 145V250L275 330L60 270Z M60 175L275 240L400 145 M275 240V330"/><path class="scene-perimeter" d="M25 190L170 55L460 145V280L285 370L25 285Z"/><g class="scene-door"><path d="M93 199l40 12v77l-40-12Z"/><circle cx="124" cy="250" r="3"/></g><g class="scene-sensors"><circle cx="177" cy="205" r="12"/><circle cx="314" cy="236" r="12"/><circle cx="360" cy="205" r="12"/></g><path class="scene-valve" d="M182 277h42m-21-18v36m-12-31 23 22m0-22-23 22"/>',
 '<path d="M45 130L180 55L455 140L325 235Z M45 130V265L325 350L455 270V140M325 235V350M180 55V180L45 265M180 180L325 235"/><g class="scene-network"><path d="M110 195L180 155L345 208L365 255L285 300L180 265L110 195"/><circle cx="110" cy="195" r="9"/><circle cx="180" cy="155" r="9"/><circle cx="345" cy="208" r="9"/><circle cx="365" cy="255" r="9"/><circle cx="285" cy="300" r="9"/></g><path class="scene-gate" d="M45 265L125 290"/><path class="scene-window" d="M355 220L420 180V247L355 287Z"/><circle class="scene-robot" cx="240" cy="275" r="10"/>'
 ];return `<svg viewBox="0 0 500 400" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2">${scenes[b]}</g></svg>`;
}
function updateScenePreview(){
 const root=document.querySelector('.story-sticky'),panel=document.querySelector('.automation-panel'),b=automationVisualBeat(),t=systemCopy[locale];
 let preview=panel.querySelector('.scene-preview');if(!preview){preview=document.createElement('div');preview.className='scene-preview';panel.querySelector('.system-map').replaceWith(preview);}
 for(const host of [preview,root.querySelector('.device-effects')]){
  if(host.dataset.scene!==String(b)){host.dataset.scene=b;host.innerHTML=`<div class="scene-photo"></div><div class="scene-diagram">${sceneDiagram()}</div><div class="scene-readout" role="status"></div>`;}
  host.setAttribute('aria-label',L(chapters[4].beats[b].label)+' · '+storyUI[locale].demo);
  host.querySelector('.scene-photo').style.backgroundImage=`url("${assets[automationSceneAsset()]}")`;
  const flags={...systemState,lit:automation.light>0,curtains:automation.curtains};Object.entries(flags).forEach(([k,v])=>{if(typeof v==='boolean')host.classList.toggle('scene-'+k,v);});
  host.style.setProperty('--scene-light',.35+automation.light*.0065);host.style.setProperty('--scene-temp',(automation.temp-16)/12);host.style.setProperty('--scene-humidity',systemState.humidity/100);host.style.setProperty('--scene-volume',systemState.volume/100);
  const readouts=[`${storyUI[locale].light} ${automation.light}% · ${automation.temp} °C`,`${automation.temp} °C · ${systemState.humidity}% · ${systemState.ventilation?t.on:t.off}`, [systemState.leak?t.valve:'',systemState.smoke?t.alarm:'',systemState.gas?t.gasOff:'',systemState.armed?storyUI[locale].armed:t.normal].filter(Boolean).join(' · '),[systemState.gate?t.gate+' '+t.open:'',systemState.window?t.window:'',systemState.robot?t.robotRun:'',systemState.irrigation?t.watering:'',systemState.tariff?t.night:''].filter(Boolean).join(' · ')||t.idle];
  host.querySelector('.scene-readout').textContent=readouts[b];
 }
}
