// Bilingual, data-owned narrative. All imagery represents a fictional design study.
const beat = (label, title, text, result, asset, view, layer, points) => ({label,title,text,result,asset,view,layer,points});
const chapters = [
 {name:['Ідея','Idea'],intro:['Перш ніж проєктувати форму, розуміємо життя, яке відбуватиметься всередині.','Before designing a form, we understand the life that will unfold within it.'],beats:[
 beat(['Місце','Place'],['Починаємо з контексту.','Start with the context.'],['Досліджуємо ділянку, оточення, рельєф і природне світло. Розглядаємо, що варто відкрити погляду, а що залишити приватним.','We study the site, surroundings, terrain and natural light. We consider which views to open up and where privacy matters.'],['Спільне розуміння можливостей і обмежень місця.','A shared understanding of the site’s opportunities and constraints.'],'model',[1,50,50],'site',[[72,34,'Природне світло','Natural light'],[55,57,'Зв’язок із ландшафтом','Landscape connection'],[31,45,'Приватність','Privacy']]),
 beat(['Ваш ритм','Your rhythm'],['Простір починається з вас.','Space begins with you.'],['Обговорюємо звички, склад родини або команди, повсякденні маршрути й очікування. Формуємо пріоритети замість набору випадкових побажань.','We discuss habits, family or team needs, everyday routes and expectations. Together we turn individual wishes into a clear set of priorities.'],['Погоджений бриф і сценарії користування простором.','An agreed brief and everyday-use scenarios.'],'model',[1.2,61,58],'zones',[[67,52,'Спільний простір','Shared space'],[28,48,'Тиха зона','Quiet zone'],[53,70,'Щоденні маршрути','Everyday routes']]),
 beat(['Варіанти','Alternatives'],['Знаходимо точний баланс.','Find the right balance.'],['Порівнюємо варіанти розміщення об’ємів, зв’язки між приміщеннями й відкритими просторами. Перевіряємо ідею до того, як вона стане деталізованим проєктом.','We compare building volumes and relationships between rooms and outdoor areas. We test the idea before developing it into a detailed design.'],['Обраний просторовий напрям із зрозумілою логікою рішень.','A selected spatial direction with a clear rationale.'],'model',[1.4,61,47],'volume',[[75,35,'Пропорції','Proportions'],[58,61,'Внутрішнє й зовнішнє','Inside and outside']]),
 beat(['Концепція','Concept'],['Одна ідея тримає все разом.','One idea holds it together.'],['Узгоджуємо характер архітектури, атмосферу інтер’єру та принципи матеріальності. Концепція стає спільною основою для всіх наступних рішень.','We align the architectural character, interior atmosphere and material principles. The concept becomes a shared foundation for every decision that follows.'],['Цілісна концепція для подальшого проєктування.','A coherent concept ready for design development.'],'house',[1,55,50],'none',[[64,34,'Характер','Character'],[40,52,'Матеріальність','Materiality']])]},
 {name:['Архітектура','Architecture'],intro:['Розвиваємо концепцію в узгоджену систему простору, конструкцій та інженерних рішень.','We develop the concept into a coordinated system of space, structure and engineering.'],beats:[
 beat(['Об’єм','Form'],['Форма має свою логіку.','Form follows a clear idea.'],['Працюємо з пропорціями, висотою й розміщенням об’ємів. Пов’язуємо архітектуру з ділянкою, підходами до будинку та краєвидами.','We work with proportion, height and the arrangement of volumes. Architecture connects to its site, arrival routes and views.'],['Узгоджене об’ємно-просторове рішення.','An agreed architectural form and spatial arrangement.'],'model',[1.1,52,50],'volume',[[72,34,'Покрівля','Roof'],[65,53,'Прозорий об’єм','Glazed volume'],[29,51,'Приватне крило','Private wing']]),
 beat(['Світло','Light'],['Світло формує архітектуру.','Light shapes architecture.'],['Розглядаємо орієнтацію, розміри скління й захист від надмірного сонця. Шукаємо баланс між відкритістю, приватністю та комфортом у різні пори року.','We consider orientation, glazing and solar shading, balancing openness, privacy and comfort throughout the year.'],['Принципи природного освітлення й сонцезахисту.','A natural-light and solar-shading strategy.'],'house',[1.15,69,39],'sun',[[73,31,'Винос покрівлі','Roof overhang'],[69,50,'Панорамне скління','Panoramic glazing'],[49,63,'Тераса','Terrace']]),
 beat(['Вузли','Junctions'],['Цілісність у місці з’єднання.','Integrity at every junction.'],['Деталізуємо взаємодію фасаду, скління, покрівлі й тераси. Узгоджуємо естетику з конструктивними та інженерними потребами.','We detail the relationships between façade, glazing, roof and terrace, coordinating aesthetics with structural and engineering needs.'],['Узгоджені принципові вузли та фасадні рішення.','Coordinated key junctions and façade decisions.'],'facade',[1,50,50],'junction',[[20,37,'Камінь','Stone'],[59,44,'Профіль скління','Glazing profile'],[73,24,'Підшивка','Soffit']]),
 beat(['Узгодження','Coordination'],['Кожна система має своє місце.','A place for every system.'],['Перевіряємо архітектурні рішення разом із суміжними розділами. Виявляємо перетини й суперечності до початку робіт, щоб задум залишався здійсненним.','We review architecture alongside related disciplines, resolving clashes before work begins so the design can be realized.'],['Погоджена основа для робочої документації та реалізації.','A coordinated basis for working documentation and realization.'],'model',[1.2,58,49],'networks',[[64,35,'Конструкції','Structure'],[53,56,'Інженерні траси','Engineering routes'],[34,51,'Планування','Planning']])]},
 {name:['Інтер’єр','Interiors'],intro:['Естетика й інженерія розвиваються разом — від планування до прихованих деталей щоденного комфорту.','Aesthetics and engineering develop together, from spatial planning to the hidden details of everyday comfort.'],beats:[
 beat(['Планування','Planning'],['Вільно рухатися. Природно жити.','Move freely. Live naturally.'],['Продумуємо функціональні зони, маршрути, меблювання й зберігання. Перевіряємо, чи зручно користуватися простором у звичайний день.','We consider functional zones, circulation, furniture and storage, checking how comfortably the space works on an ordinary day.'],['Ергономічне планування та логіка користування.','An ergonomic layout and intuitive everyday use.'],'interior',[1,55,50],'zones',[[51,52,'Відпочинок','Living'],[74,65,'Вільний прохід','Clear circulation'],[26,39,'Зберігання','Storage']]),
 beat(['Функція','Function'],['Краса в щоденних діях.','Beauty in everyday rituals.'],['Погоджуємо робочі поверхні, обладнання, місця підключення та зберігання. Меблі, механізми й техніка доповнюють одне одного.','We coordinate work surfaces, equipment, connections and storage. Furniture, mechanisms and appliances work together.'],['Узгоджені функціональні рішення та вимоги до обладнання.','Coordinated functional decisions and equipment requirements.'],'kitchen',[1,52,50],'none',[[35,55,'Робоча поверхня','Work surface'],[20,30,'Вбудовані рішення','Integrated solutions'],[34,65,'Ергономіка','Ergonomics']]),
 beat(['Інженерія','Engineering'],['Невидиме визначає комфорт.','Invisible systems. Tangible comfort.'],['Пов’язуємо електрику, освітлення, вентиляцію й клімат з інтер’єром. Враховуємо траси, доступ для обслуговування та взаємодію систем.','We integrate electrical systems, lighting, ventilation and climate with the interior, considering routes, maintenance access and system interaction.'],['Узгоджені інженерні рішення без випадкових елементів в інтер’єрі.','Integrated engineering without incidental elements in the interior.'],'interior',[1.12,57,42],'networks',[[48,22,'Освітлення','Lighting'],[77,32,'Вентиляція','Ventilation'],[53,69,'Тепла підлога','Underfloor heating']]),
 beat(['Атмосфера','Atmosphere'],['Матеріали, які відчуваєш.','Materials you can feel.'],['Добираємо фактури, колір і світлові акценти. Перевіряємо поєднання матеріалів у загальній композиції та у близькому контакті.','We select textures, colours and lighting accents, checking how materials work both in the overall composition and up close.'],['Цілісна палітра інтер’єру та принципи освітлення.','A coherent interior palette and lighting direction.'],'materials',[1.08,50,50],'none',[[34,36,'Натуральний камінь','Natural stone'],[57,44,'Дерево','Timber'],[22,51,'Текстиль','Textile']])]},
 {name:['Реалізація','Realization'],intro:['Допомагаємо зберегти задум у матеріалах, послідовності робіт і рішеннях на об’єкті. Формат відповідальності погоджуємо з вами.','We preserve the vision through materials, sequencing and decisions on site. We agree the scope of responsibility with you.'],beats:[
 beat(['Комплектація','Specification'],['Точний добір. Цілісний результат.','Careful selection. A coherent result.'],['Узгоджуємо матеріали, механізми й обладнання за характеристиками та сумісністю. Розглядаємо зразки, терміни постачання й допустимі альтернативи.','We coordinate materials, mechanisms and equipment for performance and compatibility, reviewing samples, lead times and suitable alternatives.'],['Погоджена комплектація та принципи замін.','An agreed specification and substitution principles.'],'materials',[1,50,50],'none',[[37,43,'Характеристики','Performance'],[63,53,'Поєднання','Compatibility'],[71,67,'Зразки','Samples']]),
 beat(['Послідовність','Sequence'],['Важливий порядок дій.','The sequence matters.'],['Пов’язуємо будівельні, інженерні й оздоблювальні етапи. Обговорюємо залежності між роботами, поставками та контрольними точками.','We connect construction, engineering and finishing stages, considering dependencies between work, deliveries and review points.'],['Погоджена послідовність ключових робіт.','An agreed sequence for the key work stages.'],'model',[1.12,57,50],'assembly',[[57,34,'Оболонка','Envelope'],[66,49,'Інженерія','Engineering'],[51,65,'Оздоблення','Finishes']]),
 beat(['Контроль деталей','Detail review'],['Задум зберігається в деталях.','Details preserve the vision.'],['Перевіряємо відповідність виконання погодженим рішенням у межах обраного супроводу. Уточнюємо стики, примикання та видимі елементи на об’єкті.','Within the agreed supervision scope, we review execution against the design and resolve joints, connections and visible details on site.'],['Узгоджені уточнення та зафіксовані рішення.','Coordinated refinements and recorded decisions.'],'facade',[1.35,62,51],'junction',[[58,40,'Точність примикань','Precise connections'],[38,55,'Фактура','Texture'],[76,67,'Рівні поверхонь','Surface levels']]),
 beat(['Завершення','Completion'],['Простір готовий до життя.','Ready for everyday life.'],['Звіряємо результат із задумом, обговорюємо остаточні налаштування й користування обладнанням. Завершення — це увага до того, як простір працюватиме далі.','We compare the result with the vision and discuss final settings and equipment use. Completion considers how the space will work in the years ahead.'],['Узгоджені фінальні деталі в межах обраного формату співпраці.','Agreed final details within the selected scope of work.'],'interior',[1,53,50],'none',[[47,49,'Цілісність','Integrity'],[71,62,'Готовність до користування','Ready to use']])]},
 {name:['Автоматизація','Automation'],intro:['Технології підлаштовуються під ваш ритм. Спробуйте сценарії та змініть окремі параметри в цій демонстрації.','Technology follows your rhythm. Try the scenarios and adjust individual settings in this demonstration.'],beats:[
 beat(['Сценарії','Scenarios'],['Дім відчуває ваш ритм.','A home in tune with your rhythm.'],['Повернення додому, спокійний вечір або відсутність господарів: один сценарій узгоджує кілька систем. Спробуйте змінити атмосферу цього простору.','Coming home, a quiet evening or being away: one scenario coordinates several systems. Try changing the atmosphere of this space.'],['Сценарії, погоджені з вашим способом життя.','Scenarios designed around your way of life.'],'interior',[1,55,50],'automation',[]),
 beat(['Світло й клімат','Light & climate'],['Комфорт без зайвих дій.','Comfort without extra effort.'],['Продумуємо освітлення, позонний клімат, вентиляцію та зволоження. Узгоджуємо автоматичні сценарії з можливістю простого ручного керування.','We consider lighting, zoned climate, ventilation and humidification, combining automatic scenarios with straightforward manual control.'],['Узгоджена логіка автоматичного й ручного керування.','An agreed balance of automatic and manual control.'],'interior',[1,55,50],'automation',[]),
 beat(['Безпека','Security'],['Спокій, коли вас немає.','Peace of mind when you are away.'],['Пов’язуємо захист від протікання, контроль газу й диму, замки та периметр. Поведінку в нештатних ситуаціях визначаємо окремо для кожного об’єкта.','We connect leak protection, gas and smoke monitoring, locks and perimeter systems. Responses to unusual events are defined for each individual project.'],['Погоджені сценарії моніторингу та реагування.','Agreed monitoring and response scenarios.'],'interior',[1,55,50],'automation',[]),
 beat(['Інтеграція','Integration'],['Системи працюють разом.','Systems working together.'],['Добираємо сумісні рішення для приводів, енергії, мультимедіа й побуту. Перевіряємо взаємодію сценаріїв і зручність керування перед передачею в користування.','We select compatible solutions for motorized systems, energy, multimedia and everyday tasks, checking interaction and ease of use before handover.'],['Налаштована логіка систем і зрозуміле користування.','Coordinated system logic and clear everyday operation.'],'interior',[1,55,50],'automation',[])
 ]}
];
const storyUI = {
 uk:{title:'Один простір.',subtitle:'Від ідеї до життя.',intro:'Дослідіть шлях від першого задуму до деталей, які щодня створюють комфорт.',explore:'Дослідити простір',detail:'Розкрити етап',call:'Обговорити цей етап',result:'Що отримуємо',process:'Як ми працюємо',hint:'Прокручуйте, обирайте деталі або торкайтеся позначок',concept:'Концептуальний простір',next:'Наступна деталь',previous:'Попередня деталь',preset:'Оберіть атмосферу',presets:['Вдома','Вечір','Кіно','Нікого немає'],light:'Світло',climate:'Температура',curtains:'Штори',opened:'Відкриті',closed:'Закриті',security:'Безпека',armed:'Охорона активна',home:'Режим присутності',custom:'Ваш сценарій',demo:'Інтерактивна демонстрація',points:'Деталі простору',back:'До візуалізації',summary:'Огляд послуг',reset:'Скинути налаштування'},
 en:{title:'One space.',subtitle:'From idea to everyday life.',intro:'Explore the journey from the first vision to the details that create everyday comfort.',explore:'Explore the space',detail:'Explore this stage',call:'Discuss this stage',result:'What we achieve',process:'How we work',hint:'Scroll, choose details or explore the markers',concept:'Conceptual space',next:'Next detail',previous:'Previous detail',preset:'Choose an atmosphere',presets:['At home','Evening','Cinema','Away'],light:'Lighting',climate:'Temperature',curtains:'Curtains',opened:'Open',closed:'Closed',security:'Security',armed:'Security armed',home:'Presence mode',custom:'Your scenario',demo:'Interactive demonstration',points:'Spatial details',back:'Back to visualization',summary:'Service overview',reset:'Reset controls'}
};
